In [7]:
# 导入算法包以及数据集
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.naive_bayes import MultinomialNB,BernoulliNB,GaussianNB

In [18]:
# 载入数据
iris = datasets.load_iris()
x_train,x_test,y_train,y_test = train_test_split(iris.data, iris.target)

In [19]:
mul_nb = GaussianNB()
mul_nb.fit(x_train,y_train)

GaussianNB(priors=None)

In [21]:
print(classification_report(mul_nb.predict(x_test),y_test))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        16
          1       0.85      0.92      0.88        12
          2       0.89      0.80      0.84        10

avg / total       0.92      0.92      0.92        38



In [23]:
print(confusion_matrix(mul_nb.predict(x_test),y_test))

[[16  0  0]
 [ 0 11  1]
 [ 0  2  8]]
