In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#输入数据
X = np.array([[1,0,0],
            [1,0,1],
            [1,1,0],
            [1,1,1]])
#标签
Y = np.array([[0,1,1,0]])
#权值初始化，1行3列，取值范围-1到1
V = np.random.random((3,4))*2-1
W = np.random.random((4,1))*2-1
print(V)
print(W)
#学习率设置
lr = 0.11

def sigmoid(x):
    return 1/(1+np.exp(-x))

def dsigmoid(x):
    return x*(1-x)
def update():
    global X,Y,W,V,lr
    
    L1 = sigmoid(np.dot(X,V))#隐藏层输出(4,4)
    L2 = sigmoid(np.dot(L1,W))#隐藏层输出(4,1)
    
    L2_delta = (Y.T - L2)*dsigmoid(L2)
    L1_delta = L2_delta.dot(W.T)*dsigmoid(L1)
    
    W_C = lr*L1.T.dot(L2_delta)
    V_C = lr*X.T.dot(L1_delta)
    
    W = W + W_C
    V = V + V_C

[[ 0.52814523 -0.81277753  0.91672211 -0.43156939]
 [ 0.25407775  0.09501015  0.93974741  0.82808755]
 [ 0.88612199 -0.04098404  0.18911869 -0.58918101]]
[[-0.45989517]
 [-0.3408717 ]
 [-0.59662375]
 [ 0.93427995]]


In [3]:
for i in range(20000):
    update()#更新权值
    if i%500==0:
        L1 = sigmoid(np.dot(X,V))#隐藏层输出(4,4)
        L2 = sigmoid(np.dot(L1,W))#隐藏层输出(4,1)
        print('Error:',np.mean(np.abs(Y.T-L2)))
    
L1 = sigmoid(np.dot(X,V))#隐藏层输出(4,4)
L2 = sigmoid(np.dot(L1,W))#隐藏层输出(4,1)
print(L2)

def judge(x):
    if x>=0.5:
        return 1
    else:
        return 0
    
for i in map(judge,L2):
    print(i)

Error: 0.4999368360503305
Error: 0.49616150086690775
Error: 0.4843524541297146
Error: 0.433443052139505
Error: 0.3001183170147705
Error: 0.18765743715876146
Error: 0.13506877525452243
Error: 0.10760511817529489
Error: 0.09088576516012004
Error: 0.0795810213767506
Error: 0.07137345061984744
Error: 0.06510643355302569
Error: 0.06013956687168376
Error: 0.05608927773317469
Error: 0.05271138906930433
Error: 0.04984275339709532
Error: 0.04736999751277791
Error: 0.04521173828678031
Error: 0.04330794282587882
Error: 0.041613289069070324
Error: 0.04009287155109385
Error: 0.038719336984882356
Error: 0.037470921667234806
Error: 0.036330074783085156
Error: 0.03528247241093573
Error: 0.03431629815756409
Error: 0.033421709545792676
Error: 0.03259043623298209
Error: 0.031815473370869526
Error: 0.031090844679608754
Error: 0.030411417316915372
Error: 0.02977275572003251
Error: 0.029171005115998752
Error: 0.02860279786086154
Error: 0.02806517752038115
Error: 0.027555536866040932
Error: 0.027071566879190